name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: sunpy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - main
    always: true

pr:
  autoCancel: true

stages:
  - stage: FirstPhaseTests
    displayName: Core Tests
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.8'
        submodules: false
        coverage: codecov
        toxdeps: tox-pypi-filter
        envs:
          - linux: py310

  - stage: SecondPhaseTests
    displayName: Stage 2 Tests
    dependsOn: FirstPhaseTests
    jobs:
    - template: run-tox-env.yml@OpenAstronomy
      parameters:
        default_python: '3.8'
        submodules: false
        coverage: codecov
        toxdeps: tox-pypi-filter
        libraries:
          apt:
            - graphviz
        envs:
          - macos: py38
          - windows: py39
          - linux: build_docs
            posargs: " "
            pytest: false
          - linux: py39-online
          - linux: py38-oldestdeps

  - ${{ if or(eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.Reason'], 'Manual')) }}:
    - stage: CronTests
      displayName: Cron Tests
      dependsOn: []  # Don't wait on other stages
      jobs:
      - template: run-tox-env.yml@OpenAstronomy
        parameters:
          default_python: '3.8'
          submodules: false
          coverage: codecov
          toxdeps: tox-pypi-filter
          envs:
            - linux: py310-devdeps
            - linux: py39-conda
              libraries: {}

  # On branches which aren't main, and not Pull Requests, build the wheels but only upload them on tags
  - ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), or(ne(variables['Build.SourceBranchName'], 'main'), eq(variables['Build.Reason'], 'Schedule'), eq(variables['Build.Reason'], 'Manual'))) }}:
    - stage: Release
      dependsOn: SecondPhaseTests
      jobs:
      - template: publish.yml@OpenAstronomy
        parameters:
          # Only Upload to PyPI on tags
          ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
            pypi_connection_name : 'PyPI'
          test_extras: 'tests'
          test_command: 'pytest -p no:warnings --doctest-rst --pyargs sunkit_image'
          submodules: false
          targets:
            - wheels_universal
            - sdist
